### ISSUE TITLE
corrupted release

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#1055]
With #1037 we moved our CI from Azure Pipelines to GitHub Actions, yay!

Except it broke everything. Not yay.

Something is wrong with the tarballs uploaded by the actions so I've been trying to resolve this by uploading manually created tarballs, however this is not working either.

The error message we get when downloading from what GitHub Actions produced:

```console
$ npm i -g @cloudflare/wrangler@beta
Downloading release https://github.com/cloudflare/wrangler/releases/download/v1.8.0-rc.0/wrangler-v1.8.0-rc.0-x86_64-apple-darwin.tar.gz
wrangler has been installed!
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Unpack.warn (/Users/averyharnish/Documents/work/wrangler/npm/node_modules/tar/lib/warn-mixin.js:19:40)
    at Unpack.warn (/Users/averyharnish/Documents/work/wrangler/npm/node_modules/tar/lib/unpack.js:188:18)
    at Unpack.<anonymous> (/Users/averyharnish/Documents/work/wrangler/npm/node_modules/tar/lib/parse.js:82:14)
    at Unpack.emit (events.js:215:7)
    at Unpack.[emit] (/Users/averyharnish/Documents/work/wrangler/npm/node_modules/tar/lib/parse.js:286:12)
    at Unpack.[maybeEnd] (/Users/averyharnish/Documents/work/wrangler/npm/node_modules/tar/lib/parse.js:402:17)
    at Unpack.[consumeChunk] (/Users/averyharnish/Documents/work/wrangler/npm/node_modules/tar/lib/parse.js:434:21)
    at Unpack.write (/Users/averyharnish/Documents/work/wrangler/npm/node_modules/tar/lib/parse.js:365:25)
    at Unpack.end (/Users/averyharnish/Documents/work/wrangler/npm/node_modules/tar/lib/parse.js:479:14)
    at IncomingMessage.onend (_stream_readable.js:711:10)
Emitted 'error' event on Unpack instance at:
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at Unpack.onerror (_stream_readable.js:783:9)
    at Unpack.emit (events.js:210:5)
    at Unpack.warn (/Users/averyharnish/Documents/work/wrangler/npm/node_modules/tar/lib/warn-mixin.js:19:12)
    at Unpack.warn (/Users/averyharnish/Documents/work/wrangler/npm/node_modules/tar/lib/unpack.js:188:18)
    [... lines matching original stack trace ...]
    at Unpack.[consumeChunk] (/Users/averyharnish/Documents/work/wrangler/npm/node_modules/tar/lib/parse.js:434:21) {
  recoverable: false,
  cwd: '/Users/averyharnish/.wrangler/bin',
  code: 'TAR_BAD_ARCHIVE',
  tarCode: 'TAR_BAD_ARCHIVE'
}
```

After I uploaded manually created tarballs, I'm getting a new error in the runner. Installation works fine:

```console
$ npm i -g @cloudflare/wrangler@beta
/Users/averyharnish/.nvm/versions/node/v13.1.0/bin/wrangler -> /Users/averyharnish/.nvm/versions/node/v13.1.0/lib/node_modules/@cloudflare/wrangler/run-wrangler.js

> @cloudflare/wrangler@1.8.0-rc.0 postinstall /Users/averyharnish/.nvm/versions/node/v13.1.0/lib/node_modules/@cloudflare/wrangler
> node ./install-wrangler.js

Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.8.0-rc.0/x86_64-apple-darwin
wrangler has been installed!
+ @cloudflare/wrangler@1.8.0-rc.0
added 34 packages from 21 contributors in 3.183s
~/Documents/1.8.0/wrangler-v1.8.0-rc.0-x86_64-unknown-linux-musl             4s
```

```console
$ wrangler
Error: spawnSync /Users/averyharnish/.wrangler/bin/wrangler ENOTDIR
    at Object.spawnSync (internal/child_process.js:1047:20)
    at spawnSync (child_process.js:589:24)
    at Binary.run (/Users/averyharnish/.nvm/versions/node/v13.1.0/lib/node_modules/@cloudflare/wrangler/node_modules/binary-install/src/binary.js:131:20)
    at run (/Users/averyharnish/.nvm/versions/node/v13.1.0/lib/node_modules/@cloudflare/wrangler/binary.js:32:10)
    at Object.<anonymous> (/Users/averyharnish/.nvm/versions/node/v13.1.0/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12) {
  errno: -20,
  code: 'ENOTDIR',
  syscall: 'spawnSync /Users/averyharnish/.wrangler/bin/wrangler',
  path: '/Users/averyharnish/.wrangler/bin/wrangler',
  spawnargs: []
}
```

I went in and deleted my `~/.wrangler` directory and reinstalled and then there were no issues... Not quite sure what's going on here but I'm continuing investigation.

**Comment by EverlastingBugstopper** [comment]
ok this should be fixed now - got it to work manually by making a tarball of a nested directory instead of just the top level files. now to fix it in CI
