### ISSUE TITLE
Unable to Build - thread 'main' panicked at 'could not run `npm install`: Os { code: 16, kind: Other, message: "Resource busy" }

### ISSUE THREAD

**Issue by fellars** [cloudflare/wrangler#1092]
#### Environment

* operating system: Debian 9.11 (via docker on windows)
* output of `rustc -V`: 1.34.2
* output of `node -v`: v13.9.0
* output of `wrangler -V`: wrangler 1.7.0

#### Steps to reproduce
Unable to build using `wrangler build`

#### What did you expect to see?
successful build
#### What did you see instead?

```console
$ RUST_BACKTRACE=full wrangler publish
 Using namespace for Workers Site "__app-workers_sites_assets"
 Success
thread 'main' panicked at 'could not run `npm install`: Os { code: 16, kind: Other, message: "Resource busy" }

stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new
   1: <failure::backtrace::Backtrace as core::default::Default>::default
   2: wrangler::commands::build::wranglerjs::run_npm_install
   3: wrangler::commands::build::wranglerjs::setup_build
   4: wrangler::commands::build::wranglerjs::run_build
   5: wrangler::commands::build::build
   6: wrangler::commands::publish::publish
   7: wrangler::run
   8: wrangler::main
   9: std::rt::lang_start::{{closure}}
  10: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  11: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  12: std::panicking::try
             at src/libstd/panicking.rs:270
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  13: main
', src/libcore/result.rs:1188:5
stack backtrace:
   0:           0xb1a254 - backtrace::backtrace::libunwind::trace::hdb60e04049e1ddcc
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:           0xb1a254 - backtrace::backtrace::trace_unsynchronized::h390d9f8caa87c4a6
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:           0xb1a254 - std::sys_common::backtrace::_print_fmt::hae15de093c38af7d
                               at src/libstd/sys_common/backtrace.rs:84
   3:           0xb1a254 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h109af5f2d3fa060e
                               at src/libstd/sys_common/backtrace.rs:61
   4:           0xb5965c - core::fmt::write::h5d107c846786f251
                               at src/libcore/fmt/mod.rs:1025
   5:           0xb12e07 - std::io::Write::write_fmt::hebbe4a845a69c3eb
                               at src/libstd/io/mod.rs:1426
   6:           0xb1cb8e - std::sys_common::backtrace::_print::haf8b94d5d4581012
                               at src/libstd/sys_common/backtrace.rs:65
   7:           0xb1cb8e - std::sys_common::backtrace::print::h1e13c5002c162dc0
                               at src/libstd/sys_common/backtrace.rs:50
   8:           0xb1cb8e - std::panicking::default_hook::{{closure}}::hdc11f88ccd2a4eb3
                               at src/libstd/panicking.rs:193
   9:           0xb1c881 - std::panicking::default_hook::ha3d4b1344eed6f10
                               at src/libstd/panicking.rs:210
  10:           0xb1d26b - std::panicking::rust_panic_with_hook::h3f141f4f335c2438
                               at src/libstd/panicking.rs:471
  11:           0xb1ce1e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:           0xb551fe - core::panicking::panic_fmt::hda0df35392775be8
                               at src/libcore/panicking.rs:84
  13:           0xb552f7 - core::result::unwrap_failed::h7b68c9c8d20b0fd8
                               at src/libcore/result.rs:1188
  14:           0x492fe2 - wrangler::commands::build::wranglerjs::setup_build::hd5a8af3868f9f0ad
  15:           0x490994 - wrangler::commands::build::wranglerjs::run_build::hbb1c7449e2fae433
  16:           0x493f84 - wrangler::commands::build::build::h3a92ae6b303d4482
  17:           0x45f8fd - wrangler::commands::publish::publish::hb8f3b09e9617ef64
  18:           0x40998f - wrangler::run::hf3fab558a6af69a1
  19:           0x4040d1 - wrangler::main::h119ebd8ede033035
  20:           0x40ffc7 - std::rt::lang_start::{{closure}}::h1cfb01494dad1b55
  21:           0xb1ccb3 - std::rt::lang_start_internal::{{closure}}::h2dde9b8c46a2bae5
                               at src/libstd/rt.rs:52
  22:           0xb1ccb3 - std::panicking::try::do_call::h283deab0a73ea5c5
                               at src/libstd/panicking.rs:292
  23:           0xb26baa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  24:           0xb1d6ab - std::panicking::try::hef4e7afae047e330
                               at src/libstd/panicking.rs:270
  25:           0xb1d6ab - std::panic::catch_unwind::h21142f20c3430f3e
                               at src/libstd/panic.rs:394
  26:           0xb1d6ab - std::rt::lang_start_internal::h3a042a8c7c0544dc
                               at src/libstd/rt.rs:51
  27:           0x40bef2 - main
```

**Comment by samkelleher** [comment]
Hate to +1 but yeh. @fellars  did you have a solution? My project just started this unexpectedly.

**Comment by fellars** [comment]
@samkelleher  - i never got it working. I think it had to do with running docker on windows.  I moved to running it on my ubuntu server and it worked fine (even inside a docker container using the same image as i had on my pc).  So I'm guessing its docker/windows related.
