### ISSUE TITLE
Error "Code generation from strings disallowed"

### ISSUE THREAD

**Issue by PierBover** [cloudflare/wrangler#1268]
### 🐛 Bug Report

Reporting this as suggested by @EverlastingBugstopper : https://github.com/cloudflare/wrangler/issues/1047#issuecomment-626743441

When running Webpack with `mode: "development"` wrangler throws the error:

> EvalError: Code generation from strings disallowed for this context

The solution is to disable devtools this in the config:

```
devtool: 'none',
mode: 'development'
```

I assume the error is thrown because Webpack is using `eval()` with the default dev tool option from what I read in this other issue:

https://github.com/cloudflare/workers-webpack-example/issues/1

#### Steps to reproduce

Use a custom Webpack config with `mode: "development"`.

**Comment by EverlastingBugstopper** [comment]
Thanks for filing - to be clear, this only happens with `mode: "development"`, correct? I'm sure the reason for this is because the Workers runtime does not allow the usage of `eval` and I bet that webpack's production mode either removes eval from its generated code, or the library you're using has a conditional on dev/prod that removes eval usage.

@xtuc do you think it's worth explicitly adding `devtool: none` to our default webpack config or should we document it some other way? If it's not necessary in production, should we add `devtool: none` to the default config if we implement #1084?

**Comment by PierBover** [comment]
> this only happens with mode: "development", correct?

In my case yes.

**Comment by xtuc** [comment]
webpack production mode doesn't emit eval by default, but you can also configure that in devtool. `none` might not be a good default because source-map support implies to set it to `inline-source-map`. However, I think defending against `devtool` that we know will generate invalid code for worker would be useful.

I need to look into the dev things...

**Comment by mehmetcansahin** [comment]
Hi, this bug is still ongoing. Is there a solution for this?

**Comment by willin** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/1890238/149674758-ddacd492-2ffa-4ac7-be84-afc6beebb8f7.png">

**Comment by willin** [comment]
```
EvalError: Code generation from strings disallowed for this context
    at Function (<anonymous>)
    at o (/Users/v0/Projects/remix-i18n/documents/node_modules/frenchkiss/dist/esm/frenchkiss.js:6:706)
    at g (/Users/v0/Projects/remix-i18n/documents/node_modules/frenchkiss/dist/esm/frenchkiss.js:6:1389)
    at Object.b (/Users/v0/Projects/remix-i18n/documents/node_modules/frenchkiss/dist/esm/frenchkiss.js:6:1439)
    at Index (/Users/v0/Projects/remix-i18n/documents/app/routes/$.tsx:63:18)
    at processChild (/Users/v0/Projects/remix-i18n/documents/node_modules/react-dom/cjs/react-dom-server.browser.development.js:3352:14)
    at resolve (/Users/v0/Projects/remix-i18n/documents/node_modules/react-dom/cjs/react-dom-server.browser.development.js:3269:5)
    at ReactDOMServerRenderer2.render (/Users/v0/Projects/remix-i18n/documents/node_modules/react-dom/cjs/react-dom-server.browser.development.js:3752:22)
    at ReactDOMServerRenderer2.read (/Users/v0/Projects/remix-i18n/documents/node_modules/react-dom/cjs/react-dom-server.browser.development.js:3689:29)
    at renderToString2 (/Users/v0/Projects/remix-i18n/documents/node_modules/react-dom/cjs/react-dom-server.browser.development.js:4297:27)
```

**Comment by delivey** [comment]
Still facing the issue. Mode is not development, it's not set.
