### ISSUE TITLE
Improve binary installation failure message

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler#1446]
#### Environment

* operating system:
* output of `rustc -V`: `rustc 1.44.0 (49cae5576 2020-06-01)`
* output of `node -v`: `v12.13.1`
* output of `wrangler -V`: `👷 ✨  wrangler 1.10.3`
* contents of `wrangler.toml`: n/a

#### Steps to reproduce

1. Block github.com or disconnect from your network.
1. `npx @cloudflare/wrangler whoami`
1. Find the following messages:

    <details>
    <summary>When GitHub is blocked</summary>
    <pre><code>
    ➜  ~ npx @cloudflare/wrangler whoami
    Error fetching release Request failed with status code 500
    (node:36631) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
        at createError (/Users/gregbrimble/.npm/_npx/36586/lib/node_modules/@cloudflare/wrangler/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/Users/gregbrimble/.npm/_npx/36586/lib/node_modules/@cloudflare/wrangler/node_modules/axios/lib/core/settle.js:17:12)
        at RedirectableRequest.handleResponse (/Users/gregbrimble/.npm/_npx/36586/lib/node_modules/@cloudflare/wrangler/node_modules/axios/lib/adapters/http.js:210:9)
        at RedirectableRequest.emit (events.js:210:5)
        at RedirectableRequest._processResponse (/Users/gregbrimble/.npm/_npx/36586/lib/node_modules/@cloudflare/wrangler/node_modules/follow-redirects/index.js:269:10)
        at ClientRequest.RedirectableRequest._onNativeResponse (/Users/gregbrimble/.npm/_npx/36586/lib/node_modules/@cloudflare/wrangler/node_modules/follow-redirects/index.js:50:10)
        at Object.onceWrapper (events.js:300:26)
        at ClientRequest.emit (events.js:210:5)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    (node:36631) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
    (node:36631) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    Error: spawnSync /Users/gregbrimble/.wrangler/bin/wrangler ENOENT
        at Object.spawnSync (internal/child_process.js:1041:20)
        at spawnSync (child_process.js:607:24)
        at Binary.run (/Users/gregbrimble/.npm/_npx/36586/lib/node_modules/@cloudflare/wrangler/node_modules/binary-install/src/binary.js:131:20)
        at run (/Users/gregbrimble/.npm/_npx/36586/lib/node_modules/@cloudflare/wrangler/binary.js:39:10)
        at Object.<anonymous> (/Users/gregbrimble/.npm/_npx/36586/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
        at Module._compile (internal/modules/cjs/loader.js:959:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
        at Module.load (internal/modules/cjs/loader.js:815:32)
        at Function.Module._load (internal/modules/cjs/loader.js:727:14)
        at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
      errno: 'ENOENT',
      code: 'ENOENT',
      syscall: 'spawnSync /Users/gregbrimble/.wrangler/bin/wrangler',
      path: '/Users/gregbrimble/.wrangler/bin/wrangler',
      spawnargs: [ 'whoami' ]
    }
    </code></pre>
    </details>

    <details>
    <summary>When disconnected from the network</summary>
    <pre><code>
    ➜  ~ npx @cloudflare/wrangler whoami
    Error fetching release getaddrinfo ENOTFOUND workers.cloudflare.com
    (node:47246) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND workers.cloudflare.com
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
    (node:47246) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
    (node:47246) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    Error: spawnSync /Users/gregbrimble/.wrangler/bin/wrangler ENOENT
        at Object.spawnSync (internal/child_process.js:1041:20)
        at spawnSync (child_process.js:607:24)
        at Binary.run (/Users/gregbrimble/.npm/_npx/47222/lib/node_modules/@cloudflare/wrangler/node_modules/binary-install/src/binary.js:131:20)
        at run (/Users/gregbrimble/.npm/_npx/47222/lib/node_modules/@cloudflare/wrangler/binary.js:39:10)
        at Object.<anonymous> (/Users/gregbrimble/.npm/_npx/47222/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
        at Module._compile (internal/modules/cjs/loader.js:959:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
        at Module.load (internal/modules/cjs/loader.js:815:32)
        at Function.Module._load (internal/modules/cjs/loader.js:727:14)
        at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
      errno: 'ENOENT',
      code: 'ENOENT',
      syscall: 'spawnSync /Users/gregbrimble/.wrangler/bin/wrangler',
      path: '/Users/gregbrimble/.wrangler/bin/wrangler',
      spawnargs: [ 'whoami' ]
    }
    </code></pre>
    </details>

1. Don't forget to unblock GitHub.

#### What did you expect to see?

A nice error message stating that the wrangler binary could not be pulled from GitHub and to try again later, or that we were disconnected from the network.

It would also be nice to remove the dependency on GitHub itself entirely if Cloudflare could host/mirror the binary elsewhere.

#### What did you see instead?

A big block of hard-to-read error messages.

**Comment by ispivey** [comment]
Good call, thanks for the report @GregBrimble !

**Comment by nataliescottdavidson** [comment]
@GregBrimble I believe lasso solves this problem. Ok to close?

**Comment by GregBrimble** [comment]
Looks like that failure is now being caught correctly and a better error message is thrown:

```
$ npx wrangler whoami
Error: ⚠️  Error: error sending request for url (https://api.cloudflare.com/client/v4/user): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
```

Thanks!
