### ISSUE TITLE
Error: spawnSync C:\Users\abc\.wrangler\bin\wrangler UNKNOWN

### ISSUE THREAD

**Issue by MHuiG** [cloudflare/wrangler#1523]
#### Environment

* operating system: win 10

![image](https://user-images.githubusercontent.com/38281581/91114934-a6353880-e6bb-11ea-8679-f609ec726bb6.png)

* output of `rustc -V`:
![image](https://user-images.githubusercontent.com/38281581/91113860-1d1d0200-e6b9-11ea-8cc2-71aeba43471a.png)

* output of `node -v`:
![image](https://user-images.githubusercontent.com/38281581/91113883-2c03b480-e6b9-11ea-9125-beded8751d7a.png)

* output of `wrangler -V`:
![image](https://user-images.githubusercontent.com/38281581/91113898-39b93a00-e6b9-11ea-9491-c3e38946aea9.png)

* contents of `wrangler.toml`
None
#### Steps to reproduce

1. npm i @cloudflare/wrangler -g
2. wrangler -V
```
E:\Github\ttt>npm i @cloudflare/wrangler -g
C:\Users\abc\AppData\Roaming\npm\wrangler -> C:\Users\abc\AppData\Roaming\npm\node_modules\@cloudflare\wrangler\run-wrangler.js

> @cloudflare/wrangler@1.11.0 postinstall C:\Users\abc\AppData\Roaming\npm\node_modules\@cloudflare\wrangler
> node ./install-wrangler.js

Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.11.0/x86_64-pc-windows-msvc
wrangler has been installed!


E:\Github\ttt>wrangler -V
Error: spawnSync C:\Users\abc\.wrangler\bin\wrangler UNKNOWN
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at Binary.run (C:\Users\abc\AppData\Roaming\npm\node_modules\@cloudflare\wrangler\node_modules\binary-install\src\binary.js:131:20)
    at run (C:\Users\abc\AppData\Roaming\npm\node_modules\@cloudflare\wrangler\binary.js:39:10)
    at Object.<anonymous> (C:\Users\abc\AppData\Roaming\npm\node_modules\@cloudflare\wrangler\run-wrangler.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  errno: 'UNKNOWN',
  code: 'UNKNOWN',
  syscall: 'spawnSync C:\\Users\\abc\\.wrangler\\bin\\wrangler',
  path: 'C:\\Users\\abc\\.wrangler\\bin\\wrangler',
  spawnargs: [ '-V' ]
}

E:\Github\ttt>wrangler
Error: spawnSync C:\Users\abc\.wrangler\bin\wrangler UNKNOWN
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:607:24)
    at Binary.run (C:\Users\abc\AppData\Roaming\npm\node_modules\@cloudflare\wrangler\node_modules\binary-install\src\binary.js:131:20)
    at run (C:\Users\abc\AppData\Roaming\npm\node_modules\@cloudflare\wrangler\binary.js:39:10)
    at Object.<anonymous> (C:\Users\abc\AppData\Roaming\npm\node_modules\@cloudflare\wrangler\run-wrangler.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  errno: 'UNKNOWN',
  code: 'UNKNOWN',
  syscall: 'spawnSync C:\\Users\\abc\\.wrangler\\bin\\wrangler',
  path: 'C:\\Users\\abc\\.wrangler\\bin\\wrangler',
  spawnargs: []
}

E:\Github\ttt>

```
click C:\Users\abc\\.wrangler\bin\wrangler.exe
![image](https://user-images.githubusercontent.com/38281581/91115340-98cc7e00-e6bc-11ea-9426-b942e18a992f.png)
```
This app can't run on your PC. 
to find the version that works for your PC, consult the software publisher.
                                                                                                                close
```
#### What did you expect to see?
wrangler's version

#### What did you see instead?
An Error and it dose not work.

**Comment by MHuiG** [comment]
not bug
