### ISSUE TITLE
Wrangler fails with `Error: spawnSync` `ENOENT` on WSL2

### ISSUE THREAD

**Issue by geelen** [cloudflare/wrangler#1597]
#### Environment

* operating system:

Windows WSL2 Ubuntu

`Linux Lil-Lise 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

* output of `rustc -V`:

`zsh: command not found: rustc`

* output of `node -v`:

`v14.3.0`

* output of `wrangler -V`:

```
Error: spawnSync /home/glen/.wrangler/bin/wrangler ENOENT
    at Object.spawnSync (internal/child_process.js:1070:20)
    at spawnSync (child_process.js:597:24)
    at Binary.run (/home/glen/.config/yarn/global/node_modules/binary-install/src/binary.js:131:20)
    at run (/home/glen/.config/yarn/global/node_modules/@cloudflare/wrangler/binary.js:39:10)
    at Object.<anonymous> (/home/glen/.config/yarn/global/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync /home/glen/.wrangler/bin/wrangler',
  path: '/home/glen/.wrangler/bin/wrangler',
  spawnargs: [ '-V' ]
}
```

* contents of `wrangler.toml`

N/A

#### Steps to reproduce

```
yarn global add @cloudflare/wrangler
wrangler -V
```

#### What did you expect to see?

Version number

#### What did you see instead?

Stack trace (see above).

Not sure if something is weird about my setup, this is a fairly fresh WSL2 installation but my first Rust tool I've tried.

**Comment by geelen** [comment]
Wow, just had the exact same issue with a fresh install on OSX:

```
> npm i @cloudflare/wrangler -g
/usr/local/bin/wrangler -> /usr/local/lib/node_modules/@cloudflare/wrangler/run-wrangler.js

> @cloudflare/wrangler@1.11.0 postinstall /usr/local/lib/node_modules/@cloudflare/wrangler
> node ./install-wrangler.js

Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.11.0/x86_64-apple-darwin
Error fetching release Request failed with status code 500
(node:58203) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
    at createError (/usr/local/lib/node_modules/@cloudflare/wrangler/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/@cloudflare/wrangler/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/usr/local/lib/node_modules/@cloudflare/wrangler/node_modules/axios/lib/adapters/http.js:210:9)
    at RedirectableRequest.emit (events.js:314:20)
    at RedirectableRequest._processResponse (/usr/local/lib/node_modules/@cloudflare/wrangler/node_modules/follow-redirects/index.js:269:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/usr/local/lib/node_modules/@cloudflare/wrangler/node_modules/follow-redirects/index.js:50:10)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:640:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:58203) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:58203) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ @cloudflare/wrangler@1.11.0
added 34 packages from 21 contributors in 4.435s

glen@vera
> wrangler -V                                                                            ~
Error: spawnSync /Users/glen/.wrangler/bin/wrangler ENOENT
    at Object.spawnSync (internal/child_process.js:1070:20)
    at spawnSync (child_process.js:602:24)
    at Binary.run (/usr/local/lib/node_modules/@cloudflare/wrangler/node_modules/binary-install/src/binary.js:131:20)
    at run (/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js:39:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync /Users/glen/.wrangler/bin/wrangler',
  path: '/Users/glen/.wrangler/bin/wrangler',
  spawnargs: [ '-V' ]
}

glen@vera
> uname -a
Darwin vera 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```

**Comment by geelen** [comment]
FYI: installed fine on an AWS EC2 instance

```
bitnami@glen:~$ npm i @cloudflare/wrangler -g
/opt/bitnami/nodejs/bin/wrangler -> /opt/bitnami/nodejs/lib/node_modules/@cloudflare/wrangler/run-wrangler.js

> @cloudflare/wrangler@1.11.0 postinstall /opt/bitnami/nodejs/lib/node_modules/@cloudflare/wrangler
> node ./install-wrangler.js

Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.11.0/x86_64-unknown-linux-musl
wrangler has been installed!
+ @cloudflare/wrangler@1.11.0
added 34 packages from 21 contributors in 3.035s
bitnami@glen:~$ wrangler -V
👷 ✨  wrangler 1.11.0
bitnami@glen:~$ uname -a
Linux glen 4.4.0-1102-aws #113-Ubuntu SMP Wed Jan 29 14:54:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

So it appears to be aurora borealis at this time of year at this time of day localized entirely within my kitchen 🤷

**Comment by geelen** [comment]
I think it could be a Node version issue? I have `v14.3.0` on my WSL2 installation and `v14.8.0` on my Catalina macbook. The AWS ubuntu instance has `v12.16.1`.

For anyone else hitting this, I fixed it on both Node 14 machines by running:

```
# WSL2 only, just cause I hadn't used Rust before
sudo apt install build-essential
curl https://sh.rustup.rs -sSf | sh 
source $HOME/.cargo/env
cargo install wrangler

glen@Lil-Lise
> wrangler -V                    /home/glen
👷 ✨  wrangler 1.11.0
```

On my mac, I already had Rust and Cargo, so I only needed to do:

```
cargo install wrangler

glen@vera
> wrangler -V                    ~
👷 ✨  wrangler 1.11.0
```

So I think this is probably a bug in the `@cloudflare/wrangler` JS for Node 14+, but using Cargo is fine for now. Hope this helps someone!

**Comment by viktor32** [comment]
Have the same problem and I think the problem isn't about a Node version. I use docker and during the build process I can have the success build on one machine and error with the same Dockerfile but on a different machine

**Comment by ispivey** [comment]
@geelen @viktor32 you should no longer encounter these errors when installing via npm, with the resolution of #1587. Please give it a try again at your convenience and let us know if this recurs!

@Electroid would you mind opening a new issue for more-gracefully handling errors fetching binaries? It's a great idea – but if we re-use this issue, the next person to come across it will be quite confused 😄

**Comment by viktor32** [comment]
@ispivey seems that everything is ok now. Thank you, guys!

**Comment by sshymko** [comment]
Experiencing the same issue on a clean NPM install on macOS.

```bash
brew install node
```
```bash
node -v
v17.4.0
```
```bash
npm -v
8.3.2
```
```bash
npm i @cloudflare/wrangler -g

added 22 packages, and audited 23 packages in 3s
```
```bash
wrangler -V
Error: spawnSync /Users/sshymko/.wrangler/bin/wrangler Unknown system error -86
    at Object.spawnSync (node:internal/child_process:1109:20)
    at spawnSync (node:child_process:814:24)
    at Binary.run (/opt/homebrew/lib/node_modules/@cloudflare/wrangler/binary-install.js:136:24)
    at run (/opt/homebrew/lib/node_modules/@cloudflare/wrangler/binary.js:45:10)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawnSync /Users/sshymko/.wrangler/bin/wrangler',
  path: '/Users/sshymko/.wrangler/bin/wrangler',
  spawnargs: [ '-V' ]
}
```

**Comment by KleeUT** [comment]
I'm seeing the same issue on a fresh mac osx machine.  
```
kleeut@192-168-1-7 workers % node --version
v16.4.2
kleeut@192-168-1-7 workers % npm --version
7.18.1
kleeut@192-168-1-7 workers % npm i -g @cloudflare/wrangler@latest

changed 22 packages, and audited 23 packages in 2s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
kleeut@192-168-1-7 workers % wrangler -v
Error: spawnSync /Users/kleeut/.wrangler/bin/wrangler Unknown system error -86
    at Object.spawnSync (node:internal/child_process:1086:20)
    at spawnSync (node:child_process:812:24)
    at Binary.run (/Users/kleeut/.nvm/versions/node/v16.4.2/lib/node_modules/@cloudflare/wrangler/binary-install.js:136:24)
    at run (/Users/kleeut/.nvm/versions/node/v16.4.2/lib/node_modules/@cloudflare/wrangler/binary.js:45:10)
    at Object.<anonymous> (/Users/kleeut/.nvm/versions/node/v16.4.2/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawnSync /Users/kleeut/.wrangler/bin/wrangler',
  path: '/Users/kleeut/.wrangler/bin/wrangler',
  spawnargs: [ '-v' ]
}
kleeut@192-168-1-7 workers %
```

**Comment by sshymko** [comment]
@KleeUT same here.
Looks like nobody's looking at the closed issues.
We should probably submit a new issue for this.
