### ISSUE TITLE
wranglerjs error

### ISSUE THREAD

**Issue by nataliescottdavidson** [cloudflare/wrangler#1639]
```nat@C02DD4J1MD6R landing % wrangler
Error: spawnSync /Users/nat/.wrangler/bin/wrangler ENOENT
    at Object.spawnSync (internal/child_process.js:1066:20)
    at spawnSync (child_process.js:602:24)
    at Binary.run (/usr/local/lib/node_modules/@cloudflare/wrangler/node_modules/binary-install/src/binary.js:131:20)
    at run (/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js:39:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync /Users/nat/.wrangler/bin/wrangler',
  path: '/Users/nat/.wrangler/bin/wrangler',
  spawnargs: []
}
```

**Comment by PierBover** [comment]
I'm having this same issue after trying to install wrangler using NPM:

> sudo npm i @cloudflare/wrangler -g

And then:

```
Error: spawnSync /Users/pier/.wrangler/bin/wrangler ENOENT
    at Object.spawnSync (internal/child_process.js:1041:20)
    at spawnSync (child_process.js:616:24)
    at Binary.run (/usr/local/lib/node_modules/@cloudflare/wrangler/node_modules/binary-install/src/binary.js:131:20)
    at run (/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js:39:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawnSync /Users/pier/.wrangler/bin/wrangler',
  path: '/Users/pier/.wrangler/bin/wrangler',
  spawnargs: []
}
```

I guess I will go back to manually copying the wrangler binary into `/usr/local/bin`.
