### ISSUE TITLE
dev: error when running npm install

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#1687]
#### Environment

* operating system:
* output of `rustc -V`: rustc 1.47.0 (18bf6b4f0 2020-10-07)
* output of `node -v`: v12.2.0
* output of `wrangler -V`: master
* contents of `wrangler.toml`

#### Steps to reproduce

$ cd npm && npm install

#### What did you expect to see?

No errors

#### What did you see instead?

```
$ cd npm && npm install

> @cloudflare/wrangler@1.12.3 postinstall ~cf/cloudflare/wrangler/npm
> node ./install-wrangler.js

Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.12.3/x86_64-unknown-linux-musl
Error fetching release Request failed with status code 500
(node:12349) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
    at createError (~cf/cloudflare/wrangler/npm/node_modules/axios/lib/core/createError.js:16:15)
    at settle (~cf/cloudflare/wrangler/npm/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (~cf/cloudflare/wrangler/npm/node_modules/axios/lib/adapters/http.js:210:9)
    at RedirectableRequest.emit (events.js:196:13)
    at RedirectableRequest._processResponse (~cf/cloudflare/wrangler/npm/node_modules/follow-redirects/index.js:269:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (~cf/cloudflare/wrangler/npm/node_modules/follow-redirects/index.js:50:10)
    at Object.onceWrapper (events.js:284:20)
    at ClientRequest.emit (events.js:196:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:572:23)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
(node:12349) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12349) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
added 33 packages from 20 contributors and audited 33 packages in 1.128s
found 0 vulnerabilities


```

**Comment by bengold14** [comment]
Did this issue ever get resolved? I also am having the same problem
