### ISSUE TITLE
 Not available on freebsd, Log Unsupported  FreeBSD

### ISSUE THREAD

**Issue by munderline** [cloudflare/wrangler#1735]
warning @cloudflare/wrangler > binary-install > axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
[2/4] Fetching packages...
info fsevents@2.3.1: The platform "freebsd" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "freebsd" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /usr/home/isme/workers/tf-bot/node_modules/@cloudflare/wrangler: Command failed.
Exit code: 1
Command: node ./install-wrangler.js
Arguments:
Directory: /usr/home/isme/workers/tf-bot/node_modules/@cloudflare/wrangler
Output:
/usr/home/isme/workers/tf-bot/node_modules/@cloudflare/wrangler/binary.js:19
  throw new Error(`Unsupported platform: ${type} ${arch}`);
  ^

Error: Unsupported platform: FreeBSD x64
    at getPlatform (/usr/home/isme/workers/tf-bot/node_modules/@cloudflare/wrangler/binary.js:19:9)
    at getBinary (/usr/home/isme/workers/tf-bot/node_modules/@cloudflare/wrangler/binary.js:30:20)
    at install (/usr/home/isme/workers/tf-bot/node_modules/@cloudflare/wrangler/binary.js:43:18)
    at Object.<anonymous> (/usr/home/isme/workers/tf-bot/node_modules/@cloudflare/wrangler/install-wrangler.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by xtuc** [comment]
We aren't building wrangler binaries for FreeBSD x64 at the moment. Would you mind sending a PR to create the build in our release workflow?

**Comment by munderline** [comment]
> We aren't building wrangler binaries for FreeBSD x64 at the moment. Would you mind sending a PR to create the build in our release workflow?

Sorry, I do not know
