### ISSUE TITLE
Unable to install wrangler

### ISSUE THREAD

**Issue by kokarn** [cloudflare/wrangler#1796]
### 🐛 Bug report

I'm unable to install wrangler. Most probably reason is the binary-install stuff in 1.14

#### Describe the bug

I try to install wrangler. It fails :D

```
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@cloudflare/wrangler
npm ERR! command failed
npm ERR! command sh -c node ./install-wrangler.js
npm ERR! internal/modules/cjs/loader.js:883
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module '@cloudflare/binary-install'
npm ERR! Require stack:
npm ERR! - /usr/local/lib/node_modules/@cloudflare/wrangler/binary.js
npm ERR! - /usr/local/lib/node_modules/@cloudflare/wrangler/install-wrangler.js
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:88:18)
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js:1:20)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:952:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js',
npm ERR!     '/usr/local/lib/node_modules/@cloudflare/wrangler/install-wrangler.js'
npm ERR!   ]
npm ERR! }
```
#### Reproduce the bug

`npm i -g @cloudflare/wrangler`

#### Expected behavior

It installs wrangler

#### Environment and versions

Fill out the following information about your environment.

* operating system: macOS Big Sur 11.1
* output of `wrangler -V`: 👷 ✨  wrangler 1.13.0
* output of `node -v`: v14.16.0
* content of `wrangler.toml`: N/A

**Comment by xortive** [comment]
if you `npm install -g @cloudflare/binary-install` before, does that fix it?

I managed to replicate this when testing potential solutions I was going to offer. When I did `npm cache clean --force` (note, do not run this), I was unable to install *any* version of wrangler globally, even when using `nvm`. I fixed it with the workaround above, but I'm still investigating why this is the case.

**Comment by kokarn** [comment]
This update also created another issue for me, with worker dependencies but I'll probably post another issue about that.

Running `npm install -g @cloudflare/binary-install` before did fix it, but that seems _very_ sketch?

**Comment by xortive** [comment]
@kokarn yeah, I need to figure out what's going on there.

If you uninstall completely (`npm uninstall -g @cloudflare/wrangler` and delete the @cloudflare folder from your global node_modules directory), and use `WRANGLER_INSTALL_PATH=~/.wrangler npm install -g @cloudflare/wrangler` then `WRANGLER_INSTALL_PATH=~/.wrangler wrangler --version`, does that fix it? I want to isolate the change in install location from any other issues you might be having here

**Comment by kokarn** [comment]
Correct. After removing the Cloudflare folder and running with a  set install path it works as expected

**Comment by xortive** [comment]
And if you uninstall wrangler *again*, and try installing without the set path this time, it breaks again?

This is quite unfortunate. Installing to `node_modules` is a prerequesite for making wrangler work as a devDependency and actually pin the version used for running your commands to the version used as a devDependency.

We'll have to rollback this change if it's causing problems, and have folks specify the install path to be project-local when installing as a dev-dependency instead.

**Comment by kokarn** [comment]
Yeah, it's back when I do that.

But isn't the solution to just set binary-install as a dependency to wrangler?

```
$ rm -rf ~/.wrangler
$ npm i -g @cloudflare/wrangler
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@cloudflare/wrangler
npm ERR! command failed
npm ERR! command sh -c node ./install-wrangler.js
npm ERR! internal/modules/cjs/loader.js:883
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module '@cloudflare/binary-install'
npm ERR! Require stack:
npm ERR! - /usr/local/lib/node_modules/@cloudflare/wrangler/binary.js
npm ERR! - /usr/local/lib/node_modules/@cloudflare/wrangler/install-wrangler.js
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:88:18)
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js:1:20)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:952:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js',
npm ERR!     '/usr/local/lib/node_modules/@cloudflare/wrangler/install-wrangler.js'
npm ERR!   ]
npm ERR! }
```

**Comment by xortive** [comment]
https://github.com/cloudflare/wrangler/blob/master/npm/package.json#L45 it is a dependency. I'm not sure why changing the install location changes whether or not it's able to resolve the dependency.

**Comment by kokarn** [comment]
Ah, I looked in the wrong folder, my bad.

It's indeed very strange. I'm surprised there's a difference with adding a `-g` or not

**Comment by xortive** [comment]
Either way, we'll roll back this change in 1.14.1

**Comment by kokarn** [comment]
Looking at the verbose logs, doesn't it look like it's running postinstall before it's running install for binary?
```
npm i -g --verbose @cloudflare/wrangler                                      ✔  10196  15:22:35
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'i',
npm verb cli   '-g',
npm verb cli   '--verbose',
npm verb cli   '@cloudflare/wrangler'
npm verb cli ]
npm info using npm@7.6.0
npm info using node@v14.16.0
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:/Users/oskar.risberg/repos/test/.npmrc Completed in 0ms
npm timing config:load:project Completed in 0ms
npm timing config:load:file:/Users/oskar.risberg/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 6ms
npm verb npm-session d1c49cc91c6a9001
npm timing npm:load Completed in 15ms
npm timing arborist:ctor Completed in 1ms
npm timing idealTree:init Completed in 6ms
npm timing idealTree:userRequests Completed in 2ms
npm http fetch GET 304 https://registry.npmjs.org/@cloudflare%2fwrangler 304ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/@cloudflare%2fbinary-install 224ms (from cache)
npm timing idealTree:#root Completed in 539ms
npm timing idealTree:buildDeps Completed in 541ms
npm timing idealTree:fixDepFlags Completed in 1ms
npm timing idealTree Completed in 551ms
npm timing reify:loadTrees Completed in 575ms
npm timing reify:diffTrees Completed in 3ms
npm timing reify:retireShallow Completed in 4ms
npm timing reify:createSparse Completed in 0ms
npm timing reify:loadBundles Completed in 0ms
npm timing reifyNode:node_modules/@cloudflare/wrangler Completed in 19ms
npm timing reify:unpack Completed in 19ms
npm timing reify:unretire Completed in 1ms
npm timing build:queue Completed in 1ms
npm timing build:link:node_modules/@cloudflare/wrangler Completed in 2ms
npm timing build:link Completed in 2ms
npm info run @cloudflare/wrangler@1.14.0 postinstall node_modules/@cloudflare/wrangler node ./install-wrangler.js
npm info run @cloudflare/wrangler@1.14.0 postinstall { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 3ms
npm timing reify:rollback:retireShallow Completed in 1ms
npm timing command:install Completed in 702ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1048:16)
npm verb stack     at Socket.<anonymous> (internal/child_process.js:439:11)
npm verb stack     at Socket.emit (events.js:315:20)
npm verb stack     at Pipe.<anonymous> (net.js:673:12)
npm verb pkgid @cloudflare/wrangler@1.14.0
npm verb cwd /Users/oskar.risberg/repos/test
npm verb Darwin 20.2.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "--verbose" "@cloudflare/wrangler"
npm verb node v14.16.0
npm verb npm  v7.6.0
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@cloudflare/wrangler
npm ERR! command failed
npm ERR! command sh -c node ./install-wrangler.js
npm ERR! internal/modules/cjs/loader.js:883
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module '@cloudflare/binary-install'
npm ERR! Require stack:
npm ERR! - /usr/local/lib/node_modules/@cloudflare/wrangler/binary.js
npm ERR! - /usr/local/lib/node_modules/@cloudflare/wrangler/install-wrangler.js
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:88:18)
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js:1:20)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:952:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js',
npm ERR!     '/usr/local/lib/node_modules/@cloudflare/wrangler/install-wrangler.js'
npm ERR!   ]
npm ERR! }
npm verb exit 1
npm timing npm Completed in 898ms
npm verb code 1
```

**Comment by xortive** [comment]
```
npm info run @cloudflare/wrangler@1.14.0 postinstall node_modules/@cloudflare/wrangler node ./install-wrangler.js
npm info run @cloudflare/wrangler@1.14.0 postinstall { code: 1, signal: null }
```

It looks like it's running but its failing. You're on npm 7 right? what's your `npm -v` output?

I think npm 7 is silencing the output of postinstall scripts now, because even old versions of wrangler print nothing when installing using npm 7.

**Comment by kokarn** [comment]
Ah, yeah might be. I'm on npm 7.6.0

**Comment by xortive** [comment]
@kokarn just want to confirm 1.14.1 isn't having this problem for you

if something is still broken, make sure you delete the `@cloudflare` directories in your global `node_modules` folder (should be `rm -rf /usr/local/lib/node_modules/@cloudflare` based on your output above, other folks reading should confirm the location on their machine.)

**Comment by EatonZ** [comment]
The issue still occurs upgrading from 1.14.1 -> 1.15.0.
My solution is to uninstall wrangler (`npm uninstall`), then reinstall it.
I'm on npm v7.6.
