### ISSUE TITLE
error: cargo install wrangler (1.14.1) on M1

### ISSUE THREAD

**Issue by nilslice** [cloudflare/wrangler#1800]
#### Describe the bug

Installing `wrangler` via cargo fails with the following error: 

```
error: internal compiler error: failed to process buffered lint here
   --> /Users/stevemanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/wrangler-1.14.1/src/tail/session.rs:205:19
    |
205 |         Err(e) => failure::bail!(http::format_error(e, Some(&tail_help))),
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> /Users/stevemanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/wrangler-1.14.1/src/tail/session.rs:118:17
    |
118 |                 failure::bail!(http::format_error(e, Some(&tail_help)))
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
  --> /Users/stevemanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/wrangler-1.14.1/src/tail/tunnel.rs:54:13
   |
54 | ...   failure::bail!("failed to kill cloudflared: {}\ncloudflared will eventually exit, or you can explicitly kill it by running `kill {}`", e, pid)
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
   = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: internal compiler error: failed to process buffered lint here
   --> /Users/stevemanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/wrangler-1.14.1/src/tail/session.rs:187:5
    |
187 |     failure::bail!("Could not extract tunnel url from cloudflared")
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: delayed at /rustc/04caa632dd10c2bf64b69524c7f9c4c30a436877/compiler/rustc_lint/src/early.rs:384:18
    = note: this error: internal compiler error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:974:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-nightly (04caa632d 2021-01-30) running on aarch64-apple-darwin

note: compiler flags: -C opt-level=3 -C panic=abort -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: failed to compile `wrangler v1.14.1`, intermediate artifacts can be found at `/var/folders/_g/bb8blg1n3631_c6mfk310f7w0000gn/T/cargo-installE7riU4`

Caused by:
  could not compile `wrangler`

To learn more, run the command again with --verbose.
```

#### Reproduce the bug

```sh
cargo install wrangler
```

* operating system: macos (Big Sur, using M1)
* output of `wrangler -V`: n/a can't install
* output of `node -v`: v15.7.0
* content of `wrangler.toml`: n/a

As mentioned in the error output, this is a compiler error. I will report it to the Rust team, but figured it would be good to have here for tracking purposes as well.

**Comment by nilslice** [comment]
After a couple retries, this appears to have gone away... Will close this, but if anyone else hits this please comment with we will investigate.
