### ISSUE TITLE
fail to install wrangler via npm on M1 mac

### ISSUE THREAD

**Issue by nilslice** [cloudflare/wrangler#1801]
#### Describe the bug

```sh
 ~ npm i -g @cloudflare/wrangler@1.14.1

added 23 packages, and audited 24 packages in 2s

found 0 vulnerabilities
~ wrangler
Error: spawnSync /Users/stevemanuel/.wrangler/bin/wrangler ENOENT
    at Object.spawnSync (node:internal/child_process:1086:20)
    at spawnSync (node:child_process:676:24)
    at Binary.run (/Users/stevemanuel/.nvm/versions/node/v15.11.0/lib/node_modules/@cloudflare/wrangler/node_modules/@cloudflare/binary-install/src/binary.js:122:20)
    at run (/Users/stevemanuel/.nvm/versions/node/v15.11.0/lib/node_modules/@cloudflare/wrangler/binary.js:47:10)
    at Object.<anonymous> (/Users/stevemanuel/.nvm/versions/node/v15.11.0/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync /Users/stevemanuel/.wrangler/bin/wrangler',
  path: '/Users/stevemanuel/.wrangler/bin/wrangler',
  spawnargs: []
}
```

#### Reproduce the bug

```sh
npm i @ cloudflare/wrangler -g
``` 
(intentionally added space between @ and cloudflare/wrangler as to not ping the team)

#### Expected behavior

Install wrangler.

#### Environment and versions

Fill out the following information about your environment.

* operating system: macos (Big Sur, using M1)
* output of `wrangler -V`: 
```
wrangler -V
Error: spawnSync /Users/stevemanuel/.wrangler/bin/wrangler ENOENT
    at Object.spawnSync (node:internal/child_process:1086:20)
    at spawnSync (node:child_process:676:24)
    at Binary.run (/Users/stevemanuel/.nvm/versions/node/v15.11.0/lib/node_modules/@cloudflare/wrangler/node_modules/@cloudflare/binary-install/src/binary.js:122:20)
    at run (/Users/stevemanuel/.nvm/versions/node/v15.11.0/lib/node_modules/@cloudflare/wrangler/binary.js:47:10)
    at Object.<anonymous> (/Users/stevemanuel/.nvm/versions/node/v15.11.0/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync /Users/stevemanuel/.wrangler/bin/wrangler',
  path: '/Users/stevemanuel/.wrangler/bin/wrangler',
  spawnargs: [ '-V' ]
}

```
* output of `node -v`: v15.11.0
* content of `wrangler.toml`: n/a

**Comment by tkfanswind** [comment]
same error in centos 7. Is it bug? How to fix it?

**Comment by mwwaters** [comment]
I traced the issue to no wrangler binary being in ~/.wranger/bin, which is because the install download from the URL for arm64/darwin is the cargo deploy zip. The zip for x86-64/darwin just has a README.md and wrangler binary.

arm64/darwin URL: https://workers.cloudflare.com/get-npm-wrangler-binary/1.14.1/aarch64-apple-darwin

x86-64/darwin URL: https://workers.cloudflare.com/get-npm-wrangler-binary/1.14.1/x86_64-apple-darwin

**Comment by mcapinha** [comment]
Just got bit by this, exactly the same error on a Mac M1 also.

**Comment by patrickjquinn** [comment]
I'd 'native argue support for all future and a large chunk of current macs' should be top of the priority list.

**Comment by jonathannen** [comment]
Another workaround is to regress to: `"@cloudflare/wrangler": "1.14.1"`.

Wrangler might be part of the build so dropping it from the package.json (for cargo) might not always be possible.

**Comment by nilslice** [comment]
This should be fixed in the latest release. Please give it a try and let us know if you still are hitting any errors:

`npm i -g @cloudflare/wrangler@1.16.1` or `cargo install wrangler --version 1.16.1`

**Comment by patrickjquinn** [comment]
Confirmed this working last night. Thanks for resolving this. You’ve officially unblocked my workflow 😃
