### ISSUE TITLE
NPM installation referencing a missing file creating failed installation

### ISSUE THREAD

**Issue by mrbm** [cloudflare/wrangler#1865]
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@cloudflare/wrangler
npm ERR! command failed
npm ERR! command sh -c node ./install-wrangler.js
npm ERR! Downloading release from https://workers.cloudflare.com/get-npm-wrangler-binary/1.16.0/aarch64-apple-darwin
npm ERR! Error fetching release: Request failed with status code 500

Doing this on a new computer. Got the 1.15 to install on another m1 via manually cloning and installing and manually writing the correct file paths.

Anyways...where is this file! :D

**Comment by Electroid** [comment]
Hello! We do not support M1 yet, but we are actively working on it! #1685

**Comment by nilslice** [comment]
This should be fixed in the latest release. Please give it a try and let us know if you still are hitting any errors:

`npm i -g @cloudflare/wrangler@1.16.1` or `cargo install wrangler --version 1.16.1`

**Comment by mrbm** [comment]
@nilslice I ran:
`npm i -g @cloudflare/wrangler@1.16.1`

things seemed to go without error, but now running:
`wrangler --version `

Gives me the following response:
```
Error: spawnSync /Users/mrbm/.wrangler/bin/wrangler Unknown system error -86
    at Object.spawnSync (node:internal/child_process:1086:20)
    at spawnSync (node:child_process:693:24)
    at Binary.run (/usr/local/lib/node_modules/@cloudflare/wrangler/binary-install.js:122:24)
    at run (/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawnSync /Users/mrbm/.wrangler/bin/wrangler',
  path: '/Users/mrbm/.wrangler/bin/wrangler',
  spawnargs: [ '--version' ]
}
```

**Comment by mrbm** [comment]
Update, I updated to latest big sur this morning, now running command shows the error "cannot find module 'axios' when attmepting to do the build.

Don't know if that helps...but there you go!

**Comment by mrbm** [comment]
Also heads up, uninstalled and did the cargo install, no issues.

**Comment by nilslice** [comment]
@mrbm -

> cannot find module 'axios' 

For this, you may need to delete your system-wide `node_modules` directory, it's location is specific to your OS & however you install `npm`.

With regard to this issue:
```
Error: spawnSync /Users/mrbm/.wrangler/bin/wrangler Unknown system error -86
    at Object.spawnSync (node:internal/child_process:1086:20)
    at spawnSync (node:child_process:693:24)
    at Binary.run (/usr/local/lib/node_modules/@cloudflare/wrangler/binary-install.js:122:24)
    at run (/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawnSync /Users/mrbm/.wrangler/bin/wrangler',
  path: '/Users/mrbm/.wrangler/bin/wrangler',
  spawnargs: [ '--version' ]
}
```
can you share what the output of executing:
`file /Users/mrbm/.wrangler/bin/wrangler`

If it is something like `wrangler: Mach-O 64-bit executable x86_64` then you may need to install rosetta2 (an Apple-provided instruction set translator) which will automatically run binaries. I think `-86` error number is indicating a bad cpu type. To install rosetta2, run:

```
/usr/sbin/softwareupdate --install-rosetta # will prompt you to accept some terms
```

Hopefully that solves it - otherwise there is some other problem with the way the `wrangler` binary is spawned by node. This is really helpful to know, though, so thank you for reporting!

**Comment by mrbm** [comment]
@nilslice noted
>> can you share what the output
I deleted the npm stuff now that i got cargo working. My goal would be to run everything without roseta...trying to achieve pure m1 power! So if the npm way can only be realized with rosetta i want nothing to do with it. Cargo for the win! That said hopefully some of these notes help you guys fill the gaps. M1 macs will be the future of development...battery, power, price point, its a game changer to everything.
