### ISSUE TITLE
Support for Linux/ARMC64

### ISSUE THREAD

**Issue by sirsean** [cloudflare/wrangler#2094]
### 🐛 Bug report

The wrangler tool cannot be installed on Linux/ARM64 devices, which now includes a growing number of Chromebooks.

#### Describe the bug

Upon attempting to install wrangler, it fails saying that this is an unsupported platform:

```
sirsean@penguin:~$ npm install -g @cloudflare/wrangler
npm notice 
npm notice New patch version of npm available! 7.24.0 -> 7.24.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.24.1
npm notice Run npm install -g npm@7.24.1 to update!
npm notice 
npm ERR! code 1
npm ERR! path /home/sirsean/.config/nvm/versions/node/v16.10.0/lib/node_modules/@cloudflare/wrangler
npm ERR! command failed
npm ERR! command sh -c node ./install-wrangler.js
npm ERR! /home/sirsean/.config/nvm/versions/node/v16.10.0/lib/node_modules/@cloudflare/wrangler/binary.js:20
npm ERR!   throw new Error(`Unsupported platform: ${type} ${arch}`);
npm ERR!   ^
npm ERR! 
npm ERR! Error: Unsupported platform: Linux arm64
npm ERR!     at getPlatform (/home/sirsean/.config/nvm/versions/node/v16.10.0/lib/node_modules/@cloudflare/wrangler/binary.js:20:9)
npm ERR!     at getBinary (/home/sirsean/.config/nvm/versions/node/v16.10.0/lib/node_modules/@cloudflare/wrangler/binary.js:32:20)
npm ERR!     at install (/home/sirsean/.config/nvm/versions/node/v16.10.0/lib/node_modules/@cloudflare/wrangler/binary.js:49:18)
npm ERR!     at Object.<anonymous> (/home/sirsean/.config/nvm/versions/node/v16.10.0/lib/node_modules/@cloudflare/wrangler/install-wrangler.js:4:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
npm ERR!     at node:internal/main/run_main_module:17:47

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sirsean/.npm/_logs/2021-10-03T16_32_45_348Z-debug.log
```

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Make sure you are running on Linux/ARM64*.
2. Run `npm install -g @cloudflare/wrangler`
3. See error

* Inside NodeJS:

```
> os.arch()
'arm64'
> os.type()
'Linux'
```

#### Expected behavior

I expected to successfully install the Wrangler tool and be able to use it.

#### Environment and versions

Fill out the following information about your environment.

* operating system: ChromeOS
* output of `wrangler -V`: `-bash: wrangler: command not found`
* output of `node -v`: v16.10.0
* content of `wrangler.toml`: N/A

**Comment by threepointone** [comment]
We have much wider platform support with wrangler v2. You can try it today with `npm install wrangler@beta`. More info at https://github.com/cloudflare/wrangler2 (which we'rell eventually merge back into this repo)
