### ISSUE TITLE
wrangler publish cores

### ISSUE THREAD

**Issue by DariuszOstolski** [cloudflare/wrangler#2121]
### 🐛 Bug report

```
$ wrangler --version
wrangler 1.19.4
```
```
$ node -v
v12.16.3
```

```
$ cat -p wrangler.toml
name = "my-project"
type = "webpack"
workers_dev = true
route = "some.route/*"
compatibility_date = "2021-11-03"

[site]
bucket = "./public"

[dev]
port=9000
local_protocol="https"
```

#### Describe the bug

I'm trying to publish Angular app to Cloudflare workers, when I'm executing following command:
`wrangler publish`

I'm getting coredump:
```
gdb wrangler
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2

Type "apropos word" to search for commands related to "word"...
Reading symbols from wrangler...
(gdb) set args publish
(gdb) run
Starting program: /home/darostol/.cargo/bin/wrangler publish
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6b41700 (LWP 454061)]
[Thread 0x7ffff6b41700 (LWP 454061) exited]
⬇️   Installing wranglerjs v1.19.4...
[New Thread 0x7ffff6940700 (LWP 454062)]
[Thread 0x7ffff6940700 (LWP 454062) exited]

Thread 1 "wrangler" received signal SIGSEGV, Segmentation fault.
0x00007ffff7a366f7 in SSL_get_peer_certificate () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
(gdb) bt
#0  0x00007ffff7a366f7 in SSL_get_peer_certificate () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#1  0x00007ffff7f6a179 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#2  0x00007ffff7f6e2fe in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#3  0x00007ffff7f6f14f in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#4  0x00007ffff7f1a296 in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#5  0x00007ffff7f3c8cd in ?? () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#6  0x00007ffff7f3da11 in curl_multi_perform () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#7  0x00007ffff7f33e8b in curl_easy_perform () from /usr/lib/x86_64-linux-gnu/libcurl.so.4
#8  0x0000555555bb9eba in curl::easy::handler::Easy2<H>::perform ()
#9  0x0000555555bb89c2 in curl::easy::handle::Transfer::perform ()
#10 0x0000555555bb0d62 in binary_install::curl ()
#11 0x0000555555baf842 in binary_install::Cache::_download_artifact ()
#12 0x0000555555baf686 in binary_install::Cache::download_artifact_version ()
#13 0x00005555565f55c0 in ?? ()
#14 0x0000000000000006 in ?? ()
#15 0x000000000000000a in ?? ()
#16 0x0000555555ab55c2 in wrangler::install::install ()
#17 0x00005555558f6f83 in wrangler::wranglerjs::setup_build ()
#18 0x00005555558f5db7 in wrangler::wranglerjs::run_build ()
#19 0x00005555557b1ce2 in wrangler::build::build_target ()
#20 0x00005555558f057d in wrangler::commands::publish::publish ()
#21 0x00005555559a375e in wrangler::cli::publish::publish ()
#22 0x0000000000000000 in ?? ()
(gdb) 
```
This file comes from following package:
```
$ dpkg -S /usr/lib/x86_64-linux-gnu/libcurl.so.4
libcurl4:amd64: /usr/lib/x86_64-linux-gnu/libcurl.so.4
```
And it is in following version:
```
$ apt-cache policy libcurl4 
libcurl4:
  Zainstalowana: 7.68.0-1ubuntu2.7
  Kandydująca:   7.68.0-1ubuntu2.7
  Tabela wersji:
 *** 7.68.0-1ubuntu2.7 500
        500 http://pl.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
        100 /var/lib/dpkg/status
     7.68.0-1ubuntu2 500
        500 http://pl.archive.ubuntu.com/ubuntu focal/main amd64 Packages

```

Operating system:
```
$ cat -p /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

Previously I was using 
```
$ wrangler --version
👷 ✨  wrangler 1.12.3
```
and it worked. This happens just after upgrade.
The upgrade was done using following command:
```
$ cargo install wrangler --force
```

#### Reproduce the bug

A list of steps to reproduce the bug.
1. Run `wrangler publish` just after upgrading from 1.12.3 with the file provided.

#### Expected behavior

No core assets are correctly published into Cloudflare workers.

#### Environment and versions

Fill out the following information about your environment.

**Comment by DariuszOstolski** [comment]
It seems that it was also required to update node from v12.16.3 to v16.13.0
