### ISSUE TITLE
WASM_MODULE binding missing in Module Worker

### ISSUE THREAD

**Issue by jacobmarble** [cloudflare/wrangler#2182]
#### Describe the bug

When a Module Worker includes a WebAssembly asset, the fetch handler `env` argument does not include the WASM_MODULE asset.

Consequence: it is not possible (unless I'm mistaken) to use WebAssembly with Module Workers.

#### Reproduce the bug

- Clone https://github.com/jacobmarble/cloudflare-workers-wasm-argon2-example/
- `npm install`
- start Docker
- `RUST_LOG=debug npx wrangler dev`
- confirm successful webpack+emscripten+wrangler build
- confirm `Listening on http://127.0.0.1:8787`

With debug logging enabled, notice these important log lines:

```
[2022-01-12T05:54:53Z INFO  wrangler::upload::form::project_assets] index.mjs matched by these globs ["**/*.mjs"] => ESModule
[2022-01-12T05:54:53Z INFO  wrangler::upload::form::project_assets] wasm-module.wasm matched by these globs ["**/*.wasm"] => CompiledWasm
[2022-01-12T06:00:11Z INFO  wrangler::upload::form::modules_worker] building form
[2022-01-12T06:00:11Z INFO  wrangler::upload::form::modules_worker] Form {
        boundary: "5f7b7ba92602127f-efb29f8c3e0111ed-7daae01130e080c2-67a595f5be03b185",
        parts: [
            (
                "metadata",
                Part {
                    value: Body {
                        kind: b"{\"bindings\":[],\"compatibility_date\":\"2022-01-01\",\"main_module\":\"./index.mjs\",\"migrations\":null,\"usage_model\":null}",
                    },
                    mime: Some(
                        "application/json",
                    ),
                    file_name: Some(
                        "metadata.json",
                    ),
                    headers: {},
                },
            ),
            (
                "./wasm-module.wasm",
                Part {
                    value: Body {
                        kind: Reader {
                            length: Unknown,
                        },
                    },
                    mime: Some(
                        "application/wasm",
                    ),
                    file_name: Some(
                        "./wasm-module.wasm",
                    ),
                    headers: {},
                },
            ),
            (
                "./index.mjs",
                Part {
                    value: Body {
                        kind: Reader {
                            length: Unknown,
                        },
                    },
                    mime: Some(
                        "application/javascript+module",
                    ),
                    file_name: Some(
                        "./index.mjs",
                    ),
                    headers: {},
                },
            ),
            (
                "wrangler-session-config",
                Part {
                    value: Body {
                        kind: b"{\"workers_dev\":true}",
                    },
                    mime: Some(
                        "application/json",
                    ),
                    file_name: Some(
                        "",
                    ),
                    headers: {},
                },
            ),
        ],
    }
```

To me, the above indicates that file `wasm-module.wasm` was
- built by emscripten
- copied by webpack
- discovered by Wrangler as `application/wasm`
- uploaded by Wrangler, along with `index.mjs`

However, it seems strange that a `bindings` array is empty, when WebAssembly modules are supposed to be treated as bindings:

```
                "metadata",
                Part {
                    value: Body {
                        kind: b"{\"bindings\":[],\"compatibility_date\":\"2022-01-01\",\"main_module\":\"./index.mjs\",\"migrations\":null,\"usage_model\":null}",
                    },
```

Indeed, when I send a GET request to http://localhost:8787, the following appears in the `wrangler dev` logs, suggesting that the binding is missing from the fetch handler context (this part is easier for humans to parse without `RUST_LOG=debug`):

```
request:
cf :: [object Object]
signal :: [object Object]
<snip />
env:
context:
waitUntil :: function waitUntil() { [native code] }
passThroughOnException :: function passThroughOnException() { [native code] }
TypeError: Invalid URL string.
    at ./index.mjs:1588:20
    at argon2id (./index.mjs:22:94)
    at Object.fetch (./index.mjs:2483:82) at line 1587, col 18
```

Most of the above is emitted by my fetch handler, and it shows that the `env` argument is missing any "bindings". The bug shows itself as error "Invalid URL string" because `env.WASM_MODULE` is undefined.

Following this hunch about bindings, let's look at wrangler's service worker bindings generator, and compare that to the module worker bindings generator. Notice that ServiceWorkerAssets emits bindings for wasm modules, but ModulesAssets does not:

https://github.com/cloudflare/wrangler/blob/5e8ba9d51d33a79cfd6b160270f2b7c9adddf2ad/src/upload/form/project_assets.rs#L34-L60

https://github.com/cloudflare/wrangler/blob/5e8ba9d51d33a79cfd6b160270f2b7c9adddf2ad/src/upload/form/project_assets.rs#L352-L372

#### Expected behavior

I expect some way to access my WebAssembly module from my worker code.

#### Environment and versions

Fill out the following information about your environment.

* operating system:
  * `Darwin Svalbard.lan 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64`
* output of `npx wrangler -V`: wrangler 1.19.7
* output of `node -v`: v16.13.1
* content of `wrangler.toml`:

https://github.com/jacobmarble/cloudflare-workers-wasm-argon2-example/blob/bdafa64d7f57ecfbded70f85cbb00deb92a9e999/wrangler.toml#L1-L16

**Comment by jacobmarble** [comment]
In module workers, the WebAssembly module is imported with Javascript's `import` keyword. After that, some glue is required in order to get the Emscripten Javascript to get along with CF Workers:

```javascript
import createModule from './build/wasm-module.mjs'
import module from './build/wasm-module.wasm'

...

export async function f() {
  const wasmModule = await createModule({
    instantiateWasm(info, receiveInstance) {
      const instance = new WebAssembly.Instance(module, info)
      receiveInstance(instance)
      return instance.exports
    },
    locateFile(path, scriptDirectory) {
      // scriptDirectory is undefined, so this is a
      // no-op to avoid exception "TypeError: Invalid URL string."
      return path
    },
  })

  const cEncodedHash = wasmModule._malloc(1024)
  const result = wasmModule.ccall(
    'argon2id_hash_encoded',
    ...
```
