### ISSUE TITLE
wrangler installation raise error again on M1 Mac

### ISSUE THREAD

**Issue by kjur** [cloudflare/wrangler#2240]
#### Describe the bug

Wrangler installation issue on M1 Mac seems to be fixed in #1685, however it raise an error again.

#### Reproduce the bug

sudo npm install -g @cloudflare/wrangler
Here is error log:
```
npm ERR! code 1
npm ERR! path /usr/local/share/node-17.2.0/lib/node_modules/@cloudflare/wrangler
npm ERR! command failed
npm ERR! command sh -c node ./install-wrangler.js
npm ERR! node:internal/fs/utils:344
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: EACCES: permission denied, mkdir '/Users/user1/.wrangler'
npm ERR!     at mkdirSync (node:fs:1334:3)
npm ERR!     at Binary._getInstallDirectory (/usr/local/share/node-17.2.0/lib/node_modules/@cloudflare/wrangler/binary-install.js:52:13)
npm ERR!     at Binary.install (/usr/local/share/node-17.2.0/lib/node_modules/@cloudflare/wrangler/binary-install.js:78:26)
npm ERR!     at install (/usr/local/share/node-17.2.0/lib/node_modules/@cloudflare/wrangler/binary.js:50:10)
npm ERR!     at Object.<anonymous> (/usr/local/share/node-17.2.0/lib/node_modules/@cloudflare/wrangler/install-wrangler.js:4:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1097:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
npm ERR!   errno: -13,
npm ERR!   syscall: 'mkdir',
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/user1/.wrangler'
npm ERR! }
npm ERR! 
npm ERR! Node.js v17.2.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user1/.npm/_logs/2022-04-19T15_58_14_475Z-debug-0.log
```
#### Expected behavior

Successfully installed

#### Environment and versions

* operating system:  macOS Big Sur 11.6
* output of `wrangler -V`: N/A
* output of `node -v`: v17.2.0
* content of `wrangler.toml`: N/A

**Comment by threepointone** [comment]
I think the problem here isn't about the M1, but about using sudo, and npm's permission model. 
A better solution is to use v2 of wrangler, available at `npm install wrangler` (note the lack of the `@cloudflare` scope). You can install it with `-g`, or locally to your project with `-D`. And it'll gracefully warn if it can't write to the location mentioned there. 

Closing this issue since wrangler v2 is in GA.
