### ISSUE TITLE
wrangler preview; ./worker/metadata.json not found.

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#249]
This is a regression I introduced in #237;

- `wrangler generate myproject`
- `wrangler preview` errors with 
```
thread 'main' panicked at './worker/metadata.json not found. Did you delete it?', src/commands/publish/mod.rs:248:29
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: wrangler::commands::publish::build_webpack_form::{{closure}}
             at src/commands/publish/mod.rs:248
   8: core::result::Result<T,E>::unwrap_or_else
             at /rustc/372be4f360ce42b1a10126a711189796f8440ab4/src/libcore/result.rs:766
   9: wrangler::commands::publish::build_webpack_form
             at src/commands/publish/mod.rs:246
  10: wrangler::commands::publish::preview::preview
             at src/commands/publish/preview/mod.rs:40
  11: wrangler::main
             at src/main.rs:199
  12: std::rt::lang_start::{{closure}}
             at /rustc/372be4f360ce42b1a10126a711189796f8440ab4/src/libstd/rt.rs:64
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  15: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  16: std::rt::lang_start
             at /rustc/372be4f360ce42b1a10126a711189796f8440ab4/src/libstd/rt.rs:64
  17: main
  18: __libc_start_main
  19: _start
```

We should generate the metadata file when running the preview.

**Comment by Electroid** [comment]
I ran into this, it's not just preview, it's also for build. What's the priority here? seems critical.

**Comment by granjef3** [comment]
we can move the metadata creation into `bundle.write` instead of doing it at `publish`. @xtuc does this sound like an acceptable solution?

**Comment by xtuc** [comment]
I'm not sure, it initially was (https://github.com/cloudflare/wrangler/pull/237) and prevented kv-namespace bindings to ever work.

**Comment by xtuc** [comment]
#276
