### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHeaderValue { _priv: () }', src\libcore\result.rs:997:5

### ISSUE THREAD

**Issue by steveklabnik** [cloudflare/wrangler#409]
#### Environment

* operating system: Windows 10
* output of `rustc -V`: `rustc 1.35.0 (3c235d560 2019-05-20)`
* output of `node -v`: `v10.15.3`

#### Steps to reproduce

1. create a new rust project from the template
2. put account id into wrangler.toml
3. `wrangler publish`

#### What did you expect to see?

Either my project published or an understandable error

#### What did you see instead?

with `RUST_BACTRACE`: 

```text
> wrangler publish
 Compiling your project to WebAssembly...
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.05s
[INFO]: Installing wasm-bindgen...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: :-) Done in 0.38s
[INFO]: :-) Your wasm pkg is ready to publish at .\pkg.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHeaderValue { _priv: () }', src\libcore\result.rs:997:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: BaseThreadInitThunk
  19: RtlUserThreadStart
```

**Comment by steveklabnik** [comment]
duplicate of https://github.com/cloudflare/wrangler/issues/389; closing.
